#include "common.h"

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

 This solution executes in 306 ms on my laptop

*/

/* Implemented 'TriangleNumber' in common API to provide the 'Nth Triangle Number' */

int factor( int * factor_array, int max_factors, int number )
{
  int factors = 0;
  int limit = number;
  int i;

  for (i = 1; i < limit; i++)
  {
    if ( factors >= max_factors )
      return -1; /* Safety check */

    if ( number % i == 0) /* Cleanly divisible */
    {
      int divisor = number / i;
      factor_array[factors++] = i;
      factor_array[factors++] = divisor;
      limit = divisor; /* No point continuing past this point */
    }
  }

  return factors;
}

int problem12(int argc, char ** argv)
{
  int factor_array[2048];
  int factors = 0;
  int max_factors = 0;
  int i;

  for ( i = 1; factors < 501; i++)
  {
    int triangle = TriangleNumber(i);
    factors = factor( (int*)&factor_array, sizeof(factor_array)/sizeof(int), triangle); /* Factor the Triangle number */

    if (factors < 0)
    {
      printf("Fatal: Unable to factor %d\n", triangle);
      exit(1);
    }

    if (factors > max_factors)
    {
      max_factors = factors;
      printf("The %d%s Triangle Number, %d, has %d factors\n", i, th(i), triangle, factors);
    }
  }

  return 0;
}

SINGLETON_MAIN( problem12 );
